### ISSUE TITLE
HELD Issue tracker

### ISSUE THREAD

**Issue by pw0908** [ypaul21/Clapeyron.jl#89]
Just a list of things we need to fix in our implementation of the HELD algorithm:

- [ ] Rather than use randomly generated points for initial guesses in step 1 and step 4, use sobol points
- [ ] Fix the convergence issue with VLE phases
- [ ] Loop step 8 to step 3

**Comment by ianhbell** [comment]
Does this mean that the HELD implementation is making good progress? I am very happy to hear that.

**Comment by longemen3000** [comment]
in particular this branch https://github.com/ypaul21/Clapeyron.jl/tree/HELD_TP contains the current HELD Tp-flash implementation

**Comment by longemen3000** [comment]
notes about the SRK test in the held paper:
k = 0.08
the test is at *4.053* Mpa, not 4.53. they cite (https://doi.org/10.1016/S0098-1354(02)00144-8) where the value appears

**Comment by branch171** [comment]
I have started to implement a robust version of HELD that I will provide to Clapeyron once it is complete. Some important observations. You need a robust optimisation algorithm based on trust region method with a projection operator to limit the trust region radius at each step so that the step is feasible in terms of mole fractions being in the range 0 to 1 and the implicit mole fraction (nc) is likewise. The current unbounded optimisations used are not robust in this regard. With this implemented there is some book keeping to ensure that the correct number of phases are selection on termination this requires that the system should mole balance. Its also important to reject trivial solutions, i.e. the feed composition for the optimisation as these routinely appear but if we have an unstable phase they can only appear if we are on a phase boundary like bubble or dew point and this need to be diagnosed. I would say that HELD is extremely robust even with local based optimisation but does not scale well with numbers of components.

**Comment by ianhbell** [comment]
That's exciting! I am interested in porting to teqp as well to serve as our backup flash algorithm when things don't go properly. Good to have a slow-and-steady routine to fall back on.

**Comment by pw0908** [comment]
Hi @branch171! Really exciting that you're able to get HELD to work! Did you take a look at our implementation on the HELD_TP branch?

In terms of non-linear optimization solvers, have you contacted the folks at NLSolvers.jl? They have a lot of non-linear solvers and this sounds like it could easily be incorporated into their package.

**Comment by branch171** [comment]
Yes I went trough the HELP_TP branch. Its close but needs some bookkeeping to make it robust. I managed after some effort to get HELD working I did this in C++ so I will try to port to julia, which shouldn't take long. I will try to contact NLSolvers, what we need is well documented but is somewhat bespoke due the the 1-sum(xi) used on the nc component.

**Comment by pw0908** [comment]
I'd imagine that this constraint could be handled by a Lagrangian multiplier? Although implementing that might be easier said than done.

**Comment by ianhbell** [comment]
@branch171  - I'm also in C++, is your code somewhere publicly accessible? teqp is also written in C++, so I am very interested.

**Comment by branch171** [comment]
Hi I have the first pass or HELD working now in Julia. It is detecting the correct phases and I have tested for 2 and 3 phase multicomponent mixtures including near critical mixtures. I need to improve the robustness as with default solver tolerance it’s possible to bottom out on cutting plane improvements, the lambdas converge, even when UBD and LBD difference is not converged. This is purely numerical and needs some checking. I have a solution to test for this. But using a smaller, 1e-10, dual and primary_feasibility_tolerance helps. Final step is to decide when we have good enough estimates for the phases and move to a polishing step using standard Gibbs free energy minimisation. I will post the solution for review soon.

**Comment by pw0908** [comment]
Hi @branch171 ! That's amazing! Let us know if you need any assistance in implementing it with Clapeyron / finding test cases. We developed some interesting ones in #272 with 5-phase splits.

**Comment by branch171** [comment]
I tried the 5 phase test in #272 however HELD only finds 4 phases.
The nc-1 mole fractions found and pseudo density for each phase found.  I will check if these mole balance

Cleaning completed - 4 unique solutions found UBD - LBD < 1e-8
[ HELD - Local minimisation unique solutions found: xmins_unique =
[[0.4548727757597235, 0.23272426677293365, 0.2748862219568311, 0.03427544044632414, 2.264519911384649], [0.1755220645330681, 0.0002939362804502741, 0.010074763701266642, 0.025420499330702093, 0.011202353254033803], [0.00022364816101605464, 0.003202099222383289, 1.2559588508306321e-5, 0.9942602857133142, 11.352761851933339], [0.26549192904336005, 0.3392780353311839, 0.3360172516237302, 0.05561336359512701, 2.456244989851146]]

If this is truely 5 phase it may need a tighter convergence to pick up the remainng phase. However, the mole balance check will flag if the converging supporting hyperplane is missing a phase.

**Comment by pw0908** [comment]
I double checked our code and we still struggle to converge the 5-phase system. One thing we considered is the possibility that the 5-phases aren't the most stable state at that particular concentration. Perhaps changing the concentrations would make it easier to find the 5-phase region.

Do you want to create a pull request so we can take a look?

**Comment by branch171** [comment]
Ok at 25 deg C and 1 bar with z = [0.2,0.2,0.2,0.2,0.2] the HELD solution is 3 phase

beta = [0.5876938938404989, 0.1618763543139368, 0.2504297518435952]
beta error = 1.9690915564751776e-12

Local minimisation unique solutions found: xmins_unique = 
[[0.2654593868724862, 0.33930509158168387, 0.3360173495905756, 0.055618661081808865, 2.456284042428112], [0.00022364512105595459, 0.0032022419166564914, 1.255938046185956e-5, 0.9942601340047508, 11.352756410765197], [0.1755188482059177, 0.0002939479303748309, 0.010074498963498673, 0.025420495604507508, 0.011202352113331567]]

at 5 deg C and 1 bar with z = [0.2,0.2,0.2,0.2,0.2] the HELD solution is 4 phase

beta = [0.21361197280337782, 0.17180856423952928, 0.5851353242888965, 0.029444138668127482]
beta error = 6.894484982922222e-14
Local minimisation unique solutions found: xmins_unique = 
[[0.07279293006264893, 5.949407048484334e-5, 0.0032872388855358387, 0.006489326186509545, 0.011977048629030032], [0.0002470358575130827, 0.0030006889443435275, 1.1627964783108766e-5, 0.9929868968546388, 11.508729646580196], [0.2729133478698673, 0.337945913784293, 0.33608948518937426, 0.04745863097776911, 2.479473905660217], [0.8394496560313519, 0.05867292904460286, 0.08959553776126808, 0.008165563802079496, 2.0300730240153873]]

I have not been able to find a solution that hass 5 phase. If you have an other tests let me know. I moving onto the gibbs free energy minimisation to polish the HELD determined phases.

**Comment by pw0908** [comment]
Honestly, being able to predict the existence of four phases is already pretty impressive. The failure to predict 5 phases may just come down to the thermodynamic model.

That example came from one of the 'challenges' in phase equilibrium modeling: https://doi.org/10.1021/j150471a021

**Comment by branch171** [comment]
Well I have now finished the core code. Including the polishing phase with Gibbs energy minimisation. 

Things are looking robust. I need to tidy up a bit and add a final normalisation step to ensure the reported solution moles balances to the feed moles.

I will need some QA on different cases as current settings are working but depending on small moles fractions or even high numbers of components this can cause the numerical aspects to be challenging. I find that the number of phases is often predict before the solution mole balances. It means we can jump straight to Gibbs energy minimisation reasonably early. There will be cases close to saturation points where small phase fractions or trace components then HELD can find theoretically find the answer but due to round-off errors these can cause problems.

**Comment by pw0908** [comment]
Hi @branch171,

There are a few different ways to add components in Clapeyron. You can find it in the docs here: https://clapeyronthermo.github.io/Clapeyron.jl/stable/tutorials/user_defined_parameters/

It is very likely that the methanol-water binary interaction parameters don't currently exist. While you could use the above method to define these cross-interaction parameters, one easier way would be to specify a combining rule for the association parameter:
```julia
julia> model = CPA(["water","methanol"]; assoc_options=AssocOptions(combining=:elliott))
CPA{BasicIdeal, RK{BasicIdeal, CPAAlpha, NoTranslation, vdW1fRule}} with 2 components:
 "water"
 "methanol"
RDF: Carnahan-Starling (original CPA)
Contains parameters: Mw, Tc, a, b, c1, epsilon_assoc, bondvol

julia> model.params.epsilon_assoc
AssocParam{Float64}(["water", "methanol"]) with 4 values:
("water", "e") >=< ("water", "H"): 2003.1360732366024
("methanol", "e") >=< ("water", "H"): 2473.461117631183
("methanol", "H") >=< ("water", "e"): 2473.461117631183
("methanol", "e") >=< ("methanol", "H"): 2943.7861620257627
```
The addition of this cross-association should make water and methanol miscible.

As for the association implementation, we have catches that detect the type of association scheme. If water is the only associating component, it should solve for a reduced association matrix. @longemen3000 just to confirm that this is the case? As for CPA, if I'm not wrong, we do some pre-allocations that really reduce the computational time such that it scales with the number of components. In the case of PCSAFT, the scaling should be N^2. So increasing the number of components 5 fold will increase the computational time 25 fold. The only other thing that could be responsible is that the volume calculations might be struggling. You should take a look at our michelsen implementation of tp_flash as we've done our best to make it as efficient as possible.

Best,

Pierre

**Comment by longemen3000** [comment]
Yeah, i can confirm, we do skip zero-association pairs. Scaling the amount of non-associating components should not affect the association solver time.

Also, on eos time scaling: most EoS have O(Nc²) scaling (with some exceptions, UNIFAC is O(Ng²Nc), for example). A volume calculation is around O(K), but fugacity coefficients in particular are O(Nc)*Oeos. (It depends on the AD system used, ForwardDiff uses chunks that allow O(Nc/chunk)). 

Fugacity computations also require Nc² space, that is allocated each time a fugacity coefficient is calculated (or can be passed as a cache, there is an api for that if you use `Clapeyron.lnφ`, it requires documentation)

Anyway, i suspect that the slowdown is more related to the increasing allocation of temporary caches, than to the eos scaling themselves.

**Comment by branch171** [comment]
Thanks for that. I am pretty happy with HELD now, its robust and solving even the 4 phase VLLLE. Can we slow with SAFT models but that is the price you pay for robustness.

I will remove some unneccessary print statements and then its ready for you to look at and test. I have done this in a local copied version of Calpeyron so not sure what is the best way to give you the code I could just pass you the file. I also need to integrate into your TPFlash as I find it more useful to output phase mole fractions, component mole fractions, and phase volumes. Phase volumes come for free with HELD. 

As an example here is the solution for:

components = ["methane","ethane","propane","butane","hexane","octane","methanol","water"]
model = CPA(components; assoc_options=AssocOptions(combining=:elliott))
p = 1.5e5
T = 15+273.15
zdry = [0.7,0.15,0.05,0.05,0.025,0.025]
xmeoh = 0.15
xwater = 0.05
z = append!(zdry*(1.0-xmeoh-xwater),xmeoh)
z = append!(z,xwater)

HELD Step 6 - Phases found 3
HELD Step 6 - Phase moles:
HELD Step 6 - Phase beta(1) = 0.15415313936773742
HELD Step 6 - Phase beta(2) = 0.8244849815284201
HELD Step 6 - Phase beta(3) = 0.02136187910384236
HELD Step 6 - Phase mole fraction:
HELD Step 6 - Phase x(1) = [0.0006998518363009863, 0.0008326068245187659, 0.0004220533057742065, 0.0019195768523136304, 0.002921841001255655, 0.0032618147210290516, 0.6980981568832235, 0.29184409857558424]
HELD Step 6 - Phase x(2) = [0.6789353787881671, 0.14518120659238154, 0.04816402837118285, 0.04711259378686794, 0.01847592911653333, 0.0053501069385752074, 0.05071767472873567, 0.006063081677556426]
HELD Step 6 - Phase x(3) = [0.005621808952537199, 0.008048290495055479, 0.010505682336954, 0.04028040696483823, 0.20206382311101478, 0.7062158776836108, 0.026683814423014394, 0.0005802960329751005]
HELD Step 6 - Phase volumes:
HELD Step 6 - Phase volume(1) = 3.4319660746471054e-5
HELD Step 6 - Phase volume(2) = 0.015822521095205863
HELD Step 6 - Phase volume(3) = 0.0001480359338227139

**Comment by pw0908** [comment]
Hi @branch171 

Fantastic! It's generally known / accepted that HELD will be a slower but more robust algorithm compared to other methods, even by its own developers. 

As for helping you incorporate the code into Clapeyron, there are two ways to do it. First is the easy way where you upload the relevant files here and we'll incorporate it for you. The second way would be using something called a pull request. I don't know how familiar you are with github, but what you would need to do is clone the Clapeyron repository using git on your computer, add the changes you've made there and then push the changes to github, after which you can open a pull request to the main repository. This process is a bit more challenging but we would prefer it as it would give you the appropriate credit for your contributions to the package. You can find some guidance here: 
* Cloning: https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository
* Pushing: https://docs.github.com/en/get-started/using-git/pushing-commits-to-a-remote-repository
* Pull Request: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

However, if I'm not wrong @longemen3000, even if he just sends us a copy of HELD, we can give him credit in our own commits right?

**Comment by longemen3000** [comment]
Yes, one can just add an author for a commit

**Comment by branch171** [comment]
Ok I will try the pull request route as I want to learn how. I am just running a 12 components 3 phase case to fully test convergence. But so far it's looking good. I also have some notebooks for the test cases that i can provide.

**Comment by branch171** [comment]
Some help:

If I have cloned Clapeyron main

The do I push my local clone main like this:

git push main main:HELD_TPFlash

Also I assume it's best to do a pull before the push to sync my local main:

git pull main main

Is that correct?

After I have done that I assume U do a pull request. 

Thanks

**Comment by pw0908** [comment]
Ok, I'm guessing you created a new repo with the HELD implementation in here: https://github.com/branch171/HELDTPFlash.jl? You can't do pull request across two different repositories unfortunately...

If you want to merge your changes into Clapeyron, this is what I'd recommend you do:
1. Fork Clapeyron: You'll see a button for this on the main repository page in the top right-hand side. This will create your own copy of Clapeyron. The url should be something like: https://github.com/branch171/Clapeyron.jl
2. Clone your copy: On your own copy of Clapeyron, if you press "code" you'll see options to clone the repository. On your computer, you'll probably have to type: git clone git@github.com:branch171/Clapeyron.jl.git
3. Make your changes: Just copy all your additions for HELD (ideally somewhere under src/methods/multicomponent/flash). You'll do git add and git commit.
4. Push your changes: This should be as simple as running: git push origin. You might get some issues relating to not defining origin or not setting up an ssh key. There'll be some guidance for that online.
5. Open pull requests: Once the changes are pushed onto your online copy, go under pull request and there should be an option to open a pull request with the main Clapeyron repository. If you just click that, @longemen3000 and I can handle the rest.

Hope this helps!

**Comment by branch171** [comment]
I have made the pull request
